builds:
  - main: ./cmd/go-patch-cover
    id: "cli"
    binary: go-patch-cover
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore'
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
    - go mod tidy
